baseURL = "/"
languageCode = "en-ca"
title = "Veklabs"

enableRobotsTXT = true
disableAliases = true
summaryLength = 25
Paginate = 5

staticDir = ["static"]

[menu]

 [[menu.main]]
 identifier = "products"
 name = "Products"
 url = "/products/"

 [[menu.main]]
 identifier = "services"
 name = "Services"
 url = "/services/"

 [[menu.main]]
 identifier = "testimonials"
 name = "Testimonials"
 url = "/testimonials/"

 [[menu.main]]
 identifier = "blog"
 name = "Blog"
 url = "/blog/"

[taxonomies]
 category = "category"
 type = "type"

[related]
threshold = 50.0
includeNewer = true
toLower = true

[[related.indices]]
 name = "category"
 weight = 100.0

[[related.indices]]
 name = "author"
 weight = 50.0

[params]
disallow_search_engines = false # set robots.txt to disallow everything
imgSizes = [2500, 1500, 1000, 500]

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

