baseURL = "/"
languageCode = "en-ca"
title = "Veklabs"

enableRobotsTXT = true
disableAliases = true
summaryLength = 25

staticDir = ["static"]


[params]
disallow_search_engines = false # set robots.txt to disallow everything
imgSizes = [2500, 1500, 1000, 500]

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

