[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  HUGO_VERSION = "0.95.0"
  GO_VERSION = "1.15"

[context.split1]
  command = "yarn build:split"

[context.production.environment]
  HUGO_VERSION = "0.95.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_ENV = "production"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "./plugins/generate-social-images"