local_backend: true

backend:
 name: git-gateway
 branch: Summer2024
logo_url: /assets/logo-black.svg
locale: en
media_folder: assets/images
public_folder: images
collections:
 - name: "reports"
   label: "Reports"
   folder: "content/reports"
   label_singular: "Report"
   create: true
   slug: "{{slug}}"
   delete: true
   fields:
    - { name: "image", label: "image", widget: "image" }
    - { name: "category", label: "category", widget: "string" }
    - { name: "date", label: "date", widget: "datetime" }
    - { name: "title", label: "title", widget: "string" }
    - name: "author"
      label: "author"
      widget: "relation"
      collection: "team"
      search_fields: ["name"]
      value_field: "name"
      display_fields: ["name"]
    - { name: "keywords", label: "keywords", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
 - name: pages
   label: Pages
   files:
    - label: Home
      name: home
      file: content/_index.md
      editor: { preview: false }
      fields:
       - { name: title, label: Title, widget: string }
       - name: featured
         label: Featured
         widget: list
         fields:
          - { name: brand, label: Brand Name, widget: string }
          - { name: logo, label: Logo Image, widget: image }
 - name: "team"
   label: "Team"
   folder: "content/team"
   create: true
   identifier_field: name
   slug: "{{name}}"
   label_singular: "Team Member"
   editor: { preview: true }
   fields:
    - { name: "name", label: "name", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "competencies",
       label: "competencies",
       widget: "list",
       default: [],
      }
    - { name: "title", label: "title", widget: "string" }
    - { name: "order", label: "order", widget: "number" }
    - { name: "body", label: "Body", widget: "markdown" }

 - name: "videos"
   label: "Videos"
   folder: "content/videos"
   create: true
   slug: "{{title}}"
   label_singular: "Video"
   editor: { preview: true }
   fields:
    - { name: "title", label: "title", widget: "string" }
    - { name: "videoID", label: "videoID", widget: "string" }
    - { name: "videoURL", label: "videoURL", widget: "string" }
    - { name: "previewURL", label: "previewURL", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "type",
       label: "type",
       widget: "select",
       options:
        [
         "Entertainment",
         "Promotional",
         "Social Media",
         "Corporate",
         "Short Documentary",
        ],
      }

 - name: "products"
   label: "Products"
   folder: "content/products"
   create: true
   slug: "{{title}}"
   label_singular: "Product"
   editor: { preview: false }
   fields:
    - { name: "title", label: "title", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - { name: "order", label: "order", widget: "number" }
    - { name: "speed", label: "speed", widget: "number" }
    - { name: "summary", label: "summary", widget: "text" }

 - name: "features"
   label: "Features"
   folder: "content/features"
   create: true
   slug: "{{title}}"
   label_singular: "Feature"
   editor: { preview: false }
   fields:
    - { name: "title", label: "title", widget: "string" }
    - { name: "category", label: "category", widget: "string" }
    - { name: "videoURL", label: "videoURL", widget: "string" }
    - { name: "videoID", label: "videoID", widget: "string" }
    - {
       name: "publishDate",
       label: "publishDate",
       widget: "datetime",
       date_format: "YYYY-MM-DD",
      }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "site",
       label: "site",
       widget: "string",
       pattern: ["https://.*", "Must be a valid URL"],
      }
    - { name: "body", label: "Body", widget: "markdown" }

 - name: "services"
   label: "Services"
   folder: "content/services"
   create: true
   slug: "{{title}}"
   label_singular: "Service"
   identifier_field: title
   editor: { preview: false }
   fields:
    - { name: "title", label: "title", widget: "string" }
    - { name: "page_title", label: "page_title", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - { name: "order", label: "order", widget: "number" }
    - { name: "speed", label: "speed", widget: "number" }
    - { name: "summary", label: "summary", widget: "text" }
    - { name: "body", label: "Body", widget: "markdown" }

 - name: "settings"
   label: "Settings"
   files:
    - label: "Site Settings"
      name: "config"
      file: config.toml
      editor: { preview: false }
      create: false
      delete: false
      format: toml
      fields:
       - { required: true, "Site Title", name: "title", widget: "string" }
       - { label: Site URL, name: baseURL, widget: string }
       - title: "Parameters"
         name: "params"
         widget: "object"
         fields:
          - { label: Site Description, name: description, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
             label: Items per page,
             name: Paginate,
             widget: number,
             hint: Number of items to show per page,
            }
          - label: Call to Action
            name: cta
            hint: This is the call to action that appears across the site
            widget: object
            summary: "{{fields.title}} - {{fields.description}}"
            fields:
             - { label: Title, name: title, widget: string }
             - { label: Description, name: description, widget: string }
             - { label: Button Text, name: button_title, widget: string }
             - { label: Button URL, name: button_link, widget: string }
          - {
             label: Google Analytics ID,
             name: googleAnalytics,
             widget: string,
            }
          - {
             label: Banner Shown Time,
             name: bannerShow,
             widget: number,
             hint: Time that the banner is shown for in milliseconds,
            }
          - {
             label: Open Graph Images,
             name: images,
             widget: "list",
             label_singular: "Image",
             fields: [{ label: Image, name: image, widget: "image" }],
            }
          - {
             label: Open Graph Videos,
             name: videos,
             widget: "list",
             label_singular: "Video",
             fields: [{ label: URL, name: url, widget: "string" }],
            }
