backend:
 name: git-gateway
 branch: Summer2024
media_folder: static/images
public_folder: /img
collections:
 - name: "team"
   label: "Team"
   folder: "content/team"
   create: true
   slug: "{{name}}"
   editor:
    preview: false
   fields:
    - { name: "name", label: "name", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "competencies",
       label: "competencies",
       widget: "list",
       default: [],
      }
    - { name: "title", label: "title", widget: "string" }
    - { name: "order", label: "order", widget: "number" }
