local_backend: true

backend:
 name: git-gateway
 branch: Summer2024
locale: en
media_folder: assets/images
public_folder: images
collections:
 - name: "team"
   label: "Team"
   folder: "content/team"
   create: true
   slug: "{{name}}"
   label_singular: "Team Member"
   editor:
    preview: true
   fields:
    - { name: "name", label: "name", widget: "string" }
    - { name: "image", label: "image", widget: "image" }
    - {
       name: "competencies",
       label: "competencies",
       widget: "list",
       default: [],
      }
    - { name: "title", label: "title", widget: "string" }
    - { name: "order", label: "order", widget: "number" }
    - { name: "body", label: "Body", widget: "markdown" }

 - name: "reports"
   label: "Reports"
   folder: "content/reports"
   create: true
   slug: "{{slug}}"
   delete: true
   fields:
    - { name: "image", label: "image", widget: "image" }
    - { name: "category", label: "category", widget: "string" }
    - { name: "date", label: "date", widget: "datetime" }
    - { name: "title", label: "title", widget: "string" }
    - {
       name: "author",
       label: "author",
       widget: "relation",
       collection: "team",
       search_fields: ["name"],
       value_field: "name",
       display_fields: ["name"],
      }
    - { name: "keywords", label: "keywords", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
