# local_backend: true

backend:
  name: git-gateway
  branch: hennessyevan/issue78
logo_url: /assets/logo-black.svg
locale: en
media_folder: src/images
public_folder: src/images
collections:
  - name: "reports"
    label: "Reports"
    folder: "src/content/reports"
    label_singular: "Report"
    create: true
    slug: "{{slug}}"
    delete: true
    fields:
      - { name: "image", label: "image", widget: "image" }
      - { name: "category", label: "category", widget: "string" }
      - { name: "date", label: "date", widget: "datetime" }
      - { name: "title", label: "title", widget: "string" }
      - name: "author"
        label: "author"
        widget: "relation"
        collection: "team"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
      - { name: "keywords", label: "keywords", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: "src/home.json"
        editor: { preview: false }
        create: false
        delete: false
        format: json
        fields:
          - { name: HERO_EXCERPT, label: Hero Excerpt, widget: string }
          - {
              name: "videos",
              label: "Videos",
              widget: "relation",
              multiple: true,
              collection: "videos",
              search_fields: ["title"],
              value_field: "title",
            }
          - { name: TEAM_TITLE, label: Team Title, widget: string }
          - { name: PROJECTS_FILMED, label: Projects Filmed, widget: number }
          - { name: VIDEOS_RENDERED, label: Videos Rendered, widget: number }
          - {
              name: FOOTAGE_PROCESSED_TB,
              label: Footage Processed Tb,
              widget: number,
            }
          - { name: TOTAL_VIEWS, label: Total Views, widget: number }
          - { name: CLIENT_TITLE, label: Client Title, widget: string }
          - { name: CLIENT_SUB_TITLE, label: Client Sub Title, widget: string }

      - label: Features
        name: features
        file: "src/features.json"
        editor: { preview: false }
        create: false
        delete: false
        format: json
        fields:
          - {
              name: "videos",
              label: "Videos",
              widget: "relation",
              multiple: true,
              collection: "videos",
              search_fields: ["title"],
              value_field: "title",
            }

      - label: Clients
        name: clients
        file: "src/clients.json"
        editor: { preview: false }
        create: false
        delete: false
        format: json
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "subtitle", label: "Subtitle", widget: "string" }
          - { name: "contact_link", label: "Contact Link", widget: "string" }

  - name: "team"
    label: "Team"
    folder: "src/content/team"
    create: true
    identifier_field: name
    slug: "{{name}}"
    label_singular: "Team Member"
    editor: { preview: false }
    fields:
      - { name: "name", label: "name", widget: "string" }
      - { name: "image", label: "image", widget: "image" }
      - {
          name: "competencies",
          label: "competencies",
          widget: "list",
          default: [],
        }
      - { name: "title", label: "title", widget: "string" }
      - { name: "order", label: "order", widget: "number" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "videos"
    label: "Videos"
    folder: "src/content/videos"
    create: true
    slug: "{{title}}"
    label_singular: "Video"
    editor: { preview: false }
    fields:
      - { name: "title", label: "title", widget: "string", required: true }
      - { name: "videoID", label: "videoID", widget: "string" }
      - {
          name: "videoURL",
          label: "videoURL",
          widget: "string",
          required: true,
        }
      - { name: "previewURL", label: "previewURL", widget: "string" }
      - {
          name: meta,
          label: Metadata,
          widget: list,
          summary: "{{fields.label}}",
          fields:
            [
              { name: label, label: Label, widget: string },
              { name: value, label: Value, widget: string },
            ],
        }
      - {
          name: "publishDate",
          label: "publishDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
        }
      - {
          name: "site",
          label: "site",
          widget: "string",
          pattern: ["https://.*", "Must be a valid URL"],
        }
      - {
          name: "type",
          label: "type",
          widget: "relation",
          collection: "categories",
          hint: "Select the category for this video. [Create a new category](/admin#/collections/categories/new) if needed.",
          required: true,
          value_field: "title",
          search_fields: ["title"],
        }
      - { name: "image", label: "image", widget: "image", required: true }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    slug: "{{title}}"
    label_singular: "Service"
    identifier_field: title
    editor: { preview: false }
    fields:
      - { name: "title", label: "title", widget: "string" }
      - { name: "page_title", label: "page_title", widget: "string" }
      - { name: "image", label: "image", widget: "image" }
      - { name: "order", label: "order", widget: "number" }
      - { name: "speed", label: "speed", widget: "number" }
      - { name: "summary", label: "summary", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "categories"
    label: "Categories"
    folder: "src/content/categories"
    create: true
    slug: "{{title}}"
    label_singular: "Category"
    identifier_field: title
    editor: { preview: false }
    fields:
      - { name: "title", label: "title", widget: "string" }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Settings"
        name: "config"
        file: "src/config.json"
        editor: { preview: false }
        create: false
        delete: false
        format: json
        fields:
          - {
              name: EMAIL,
              label: Email,
              widget: string,
              pattern: ["[^@]+@[^@]+", "Must be an email"],
            }
          - {
              name: PHONE,
              label: Phone,
              widget: string,
              pattern:
                [
                  "[0-9]{3}-[0-9]{3}-[0-9]{4}",
                  "Phone number must be in the format 123-456-7890",
                ],
            }
          - { name: subtitle, label: Subtitle, widget: string }
          - { name: description, label: Description, widget: string }
          - { name: FOOTER_PRETEXT, label: Footer Pretext, widget: string }
          - { required: true, "Site Title", name: "title", widget: "string" }
          - { label: Site URL, name: baseURL, widget: string }
          - {
              label: Google Analytics ID,
              name: googleAnalytics,
              widget: string,
            }
          - {
              label: Open Graph Images,
              name: images,
              widget: "list",
              label_singular: "Image",
              fields: [{ label: Image, name: image, widget: "image" }],
            }
          - {
              label: Open Graph Videos,
              name: videos,
              widget: "list",
              label_singular: "Video",
              fields: [{ label: URL, name: url, widget: "string" }],
            }
